import type { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
  HiHashtag,
} from "react-icons/hi2";

import { VscVscode } from "react-icons/vsc";
import { HapiIcon } from "../components/icons/HapiIcon";
import { GroqIcon } from "../components/icons/GroqIcon";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
  PiBriefcaseDuotone,
  PiMedalDuotone,
  PiIdentificationCardDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiPython,
  SiReact,
  SiVuedotjs,
  SiAngular,
  SiTailwindcss,
  SiBootstrap,
  SiHtml5,
  SiGo,
  SiTypescript,
  SiMysql,
  SiGitlab,
  SiGit,
  SiVsco,
  SiStreamlit,
  SiRedis,
  SiElasticsearch,
  SiCplusplus,
  SiSass,
  SiFlutter,
  SiDart,
  SiNodedotjs,
  SiAmazonwebservices,
  SiRedux,
  SiPhp,
  SiWordpress,
  SiThreedotjs,
  SiLangchain,
  SiTensorflow,
  SiExpress,
  SiKeras,
  SiOpenai,
  SiPostman,
  SiMeta,
  SiGoogle,
  SiPostgresql,
  SiGooglegemini,
  SiStrapi,
} from "react-icons/si";

import { FaDiscord, FaGithub, FaLinkedin, FaX, FaThreads, FaInstagram, FaXTwitter, FaFacebook, FaPinterest, FaWhatsapp, FaReddit, FaTelegram, FaJava, } from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  python: SiPython,
  react: SiReact,
  vue: SiVuedotjs,
  angular: SiAngular,
  tailwind: SiTailwindcss,
  bootstrap: SiBootstrap,
  html: SiHtml5,
  golang: SiGo,
  typescript: SiTypescript,
  sql: SiMysql,
  gitlab: SiGitlab,
  git: SiGit,
  vscode: VscVscode,
  streamlit: SiStreamlit,
  redis: SiRedis,
  elasticsearch: SiElasticsearch,
  cplusplus: SiCplusplus,
  scss: SiSass,
  flutter: SiFlutter,
  dart: SiDart,
  nodejs: SiNodedotjs,
  aws: SiAmazonwebservices,
  redux: SiRedux,
  php: SiPhp,
  wordpress: SiWordpress,
  threejs: SiThreedotjs,
  langchain: SiLangchain,
  tensorflow: SiTensorflow,
  express: SiExpress,
  keras: SiKeras,
  openai: SiOpenai,
  postman: SiPostman,
  meta: SiMeta,
  google: SiGoogle,
  postgresql: SiPostgresql,
  gemini: SiGooglegemini,
  java: FaJava,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
  hapi: HapiIcon,
  groq: GroqIcon,
  hashtag: HiHashtag,
  work: PiBriefcaseDuotone,
  certificate: PiMedalDuotone,
  cv: PiIdentificationCardDuotone,
  strapi: SiStrapi,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
